// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proxy/gmesh/inbound/config.proto

package inbound

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protocol "github.com/xtls/xray-core/common/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config_Mode int32

const (
	Config_COMPATIBILITY Config_Mode = 0
	Config_RELAY         Config_Mode = 1
	Config_LEAF          Config_Mode = 2
)

// Enum value maps for Config_Mode.
var (
	Config_Mode_name = map[int32]string{
		0: "COMPATIBILITY",
		1: "RELAY",
		2: "LEAF",
	}
	Config_Mode_value = map[string]int32{
		"COMPATIBILITY": 0,
		"RELAY":         1,
		"LEAF":          2,
	}
)

func (x Config_Mode) Enum() *Config_Mode {
	p := new(Config_Mode)
	*p = x
	return p
}

func (x Config_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Config_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_gmesh_inbound_config_proto_enumTypes[0].Descriptor()
}

func (Config_Mode) Type() protoreflect.EnumType {
	return &file_proxy_gmesh_inbound_config_proto_enumTypes[0]
}

func (x Config_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Config_Mode.Descriptor instead.
func (Config_Mode) EnumDescriptor() ([]byte, []int) {
	return file_proxy_gmesh_inbound_config_proto_rawDescGZIP(), []int{1, 0}
}

type Fallback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Alpn          string                 `protobuf:"bytes,2,opt,name=alpn,proto3" json:"alpn,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Dest          string                 `protobuf:"bytes,5,opt,name=dest,proto3" json:"dest,omitempty"`
	Xver          uint64                 `protobuf:"varint,6,opt,name=xver,proto3" json:"xver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fallback) Reset() {
	*x = Fallback{}
	mi := &file_proxy_gmesh_inbound_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fallback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fallback) ProtoMessage() {}

func (x *Fallback) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_gmesh_inbound_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fallback.ProtoReflect.Descriptor instead.
func (*Fallback) Descriptor() ([]byte, []int) {
	return file_proxy_gmesh_inbound_config_proto_rawDescGZIP(), []int{0}
}

func (x *Fallback) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Fallback) GetAlpn() string {
	if x != nil {
		return x.Alpn
	}
	return ""
}

func (x *Fallback) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Fallback) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Fallback) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *Fallback) GetXver() uint64 {
	if x != nil {
		return x.Xver
	}
	return 0
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*protocol.User       `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	Fallbacks     []*Fallback            `protobuf:"bytes,2,rep,name=fallbacks,proto3" json:"fallbacks,omitempty"`
	Decryption    string                 `protobuf:"bytes,3,opt,name=decryption,proto3" json:"decryption,omitempty"`
	XorMode       uint32                 `protobuf:"varint,4,opt,name=xorMode,proto3" json:"xorMode,omitempty"`
	Padding       string                 `protobuf:"bytes,5,opt,name=padding,proto3" json:"padding,omitempty"`
	Mode          Config_Mode            `protobuf:"varint,6,opt,name=mode,proto3,enum=xray.proxy.gmesh.inbound.Config_Mode" json:"mode,omitempty"`
	NodeId        string                 `protobuf:"bytes,7,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Version       uint32                 `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	Discovery     *Config_Discovery      `protobuf:"bytes,9,opt,name=discovery,proto3" json:"discovery,omitempty"`
	Routing       *Config_Routing        `protobuf:"bytes,10,opt,name=routing,proto3" json:"routing,omitempty"`
	SecondsFrom   int64                  `protobuf:"varint,11,opt,name=seconds_from,json=secondsFrom,proto3" json:"seconds_from,omitempty"`
	SecondsTo     int64                  `protobuf:"varint,12,opt,name=seconds_to,json=secondsTo,proto3" json:"seconds_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proxy_gmesh_inbound_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_gmesh_inbound_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proxy_gmesh_inbound_config_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetClients() []*protocol.User {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *Config) GetFallbacks() []*Fallback {
	if x != nil {
		return x.Fallbacks
	}
	return nil
}

func (x *Config) GetDecryption() string {
	if x != nil {
		return x.Decryption
	}
	return ""
}

func (x *Config) GetXorMode() uint32 {
	if x != nil {
		return x.XorMode
	}
	return 0
}

func (x *Config) GetPadding() string {
	if x != nil {
		return x.Padding
	}
	return ""
}

func (x *Config) GetMode() Config_Mode {
	if x != nil {
		return x.Mode
	}
	return Config_COMPATIBILITY
}

func (x *Config) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Config) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Config) GetDiscovery() *Config_Discovery {
	if x != nil {
		return x.Discovery
	}
	return nil
}

func (x *Config) GetRouting() *Config_Routing {
	if x != nil {
		return x.Routing
	}
	return nil
}

func (x *Config) GetSecondsFrom() int64 {
	if x != nil {
		return x.SecondsFrom
	}
	return 0
}

func (x *Config) GetSecondsTo() int64 {
	if x != nil {
		return x.SecondsTo
	}
	return 0
}

type Config_Discovery struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LanDiscovery         bool                   `protobuf:"varint,1,opt,name=lan_discovery,json=lanDiscovery,proto3" json:"lan_discovery,omitempty"`
	AnnouncementInterval uint32                 `protobuf:"varint,2,opt,name=announcement_interval,json=announcementInterval,proto3" json:"announcement_interval,omitempty"`
	DhtNetworkId         string                 `protobuf:"bytes,3,opt,name=dht_network_id,json=dhtNetworkId,proto3" json:"dht_network_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Config_Discovery) Reset() {
	*x = Config_Discovery{}
	mi := &file_proxy_gmesh_inbound_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config_Discovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Discovery) ProtoMessage() {}

func (x *Config_Discovery) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_gmesh_inbound_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Discovery.ProtoReflect.Descriptor instead.
func (*Config_Discovery) Descriptor() ([]byte, []int) {
	return file_proxy_gmesh_inbound_config_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Config_Discovery) GetLanDiscovery() bool {
	if x != nil {
		return x.LanDiscovery
	}
	return false
}

func (x *Config_Discovery) GetAnnouncementInterval() uint32 {
	if x != nil {
		return x.AnnouncementInterval
	}
	return 0
}

func (x *Config_Discovery) GetDhtNetworkId() string {
	if x != nil {
		return x.DhtNetworkId
	}
	return ""
}

type Config_Routing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxPeers      uint32                 `protobuf:"varint,1,opt,name=max_peers,json=maxPeers,proto3" json:"max_peers,omitempty"`
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	RouteTtl      uint32                 `protobuf:"varint,3,opt,name=route_ttl,json=routeTtl,proto3" json:"route_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config_Routing) Reset() {
	*x = Config_Routing{}
	mi := &file_proxy_gmesh_inbound_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config_Routing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Routing) ProtoMessage() {}

func (x *Config_Routing) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_gmesh_inbound_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Routing.ProtoReflect.Descriptor instead.
func (*Config_Routing) Descriptor() ([]byte, []int) {
	return file_proxy_gmesh_inbound_config_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Config_Routing) GetMaxPeers() uint32 {
	if x != nil {
		return x.MaxPeers
	}
	return 0
}

func (x *Config_Routing) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *Config_Routing) GetRouteTtl() uint32 {
	if x != nil {
		return x.RouteTtl
	}
	return 0
}

var File_proxy_gmesh_inbound_config_proto protoreflect.FileDescriptor

const file_proxy_gmesh_inbound_config_proto_rawDesc = "" +
	"\n" +
	" proxy/gmesh/inbound/config.proto\x12\x18xray.proxy.gmesh.inbound\x1a\x1acommon/protocol/user.proto\"\x82\x01\n" +
	"\bFallback\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04alpn\x18\x02 \x01(\tR\x04alpn\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04dest\x18\x05 \x01(\tR\x04dest\x12\x12\n" +
	"\x04xver\x18\x06 \x01(\x04R\x04xver\"\xb1\x06\n" +
	"\x06Config\x124\n" +
	"\aclients\x18\x01 \x03(\v2\x1a.xray.common.protocol.UserR\aclients\x12@\n" +
	"\tfallbacks\x18\x02 \x03(\v2\".xray.proxy.gmesh.inbound.FallbackR\tfallbacks\x12\x1e\n" +
	"\n" +
	"decryption\x18\x03 \x01(\tR\n" +
	"decryption\x12\x18\n" +
	"\axorMode\x18\x04 \x01(\rR\axorMode\x12\x18\n" +
	"\apadding\x18\x05 \x01(\tR\apadding\x129\n" +
	"\x04mode\x18\x06 \x01(\x0e2%.xray.proxy.gmesh.inbound.Config.ModeR\x04mode\x12\x17\n" +
	"\anode_id\x18\a \x01(\tR\x06nodeId\x12\x18\n" +
	"\aversion\x18\b \x01(\rR\aversion\x12H\n" +
	"\tdiscovery\x18\t \x01(\v2*.xray.proxy.gmesh.inbound.Config.DiscoveryR\tdiscovery\x12B\n" +
	"\arouting\x18\n" +
	" \x01(\v2(.xray.proxy.gmesh.inbound.Config.RoutingR\arouting\x12!\n" +
	"\fseconds_from\x18\v \x01(\x03R\vsecondsFrom\x12\x1d\n" +
	"\n" +
	"seconds_to\x18\f \x01(\x03R\tsecondsTo\x1a\x8b\x01\n" +
	"\tDiscovery\x12#\n" +
	"\rlan_discovery\x18\x01 \x01(\bR\flanDiscovery\x123\n" +
	"\x15announcement_interval\x18\x02 \x01(\rR\x14announcementInterval\x12$\n" +
	"\x0edht_network_id\x18\x03 \x01(\tR\fdhtNetworkId\x1a_\n" +
	"\aRouting\x12\x1b\n" +
	"\tmax_peers\x18\x01 \x01(\rR\bmaxPeers\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\x12\x1b\n" +
	"\troute_ttl\x18\x03 \x01(\rR\brouteTtl\".\n" +
	"\x04Mode\x12\x11\n" +
	"\rCOMPATIBILITY\x10\x00\x12\t\n" +
	"\x05RELAY\x10\x01\x12\b\n" +
	"\x04LEAF\x10\x02Bj\n" +
	"\x1ccom.xray.proxy.gmesh.inboundP\x01Z-github.com/xtls/xray-core/proxy/gmesh/inbound\xaa\x02\x18Xray.Proxy.GMesh.Inboundb\x06proto3"

var (
	file_proxy_gmesh_inbound_config_proto_rawDescOnce sync.Once
	file_proxy_gmesh_inbound_config_proto_rawDescData []byte
)

func file_proxy_gmesh_inbound_config_proto_rawDescGZIP() []byte {
	file_proxy_gmesh_inbound_config_proto_rawDescOnce.Do(func() {
		file_proxy_gmesh_inbound_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_gmesh_inbound_config_proto_rawDesc), len(file_proxy_gmesh_inbound_config_proto_rawDesc)))
	})
	return file_proxy_gmesh_inbound_config_proto_rawDescData
}

var file_proxy_gmesh_inbound_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proxy_gmesh_inbound_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proxy_gmesh_inbound_config_proto_goTypes = []any{
	(Config_Mode)(0),         // 0: xray.proxy.gmesh.inbound.Config.Mode
	(*Fallback)(nil),         // 1: xray.proxy.gmesh.inbound.Fallback
	(*Config)(nil),           // 2: xray.proxy.gmesh.inbound.Config
	(*Config_Discovery)(nil), // 3: xray.proxy.gmesh.inbound.Config.Discovery
	(*Config_Routing)(nil),   // 4: xray.proxy.gmesh.inbound.Config.Routing
	(*protocol.User)(nil),    // 5: xray.common.protocol.User
}
var file_proxy_gmesh_inbound_config_proto_depIdxs = []int32{
	5, // 0: xray.proxy.gmesh.inbound.Config.clients:type_name -> xray.common.protocol.User
	1, // 1: xray.proxy.gmesh.inbound.Config.fallbacks:type_name -> xray.proxy.gmesh.inbound.Fallback
	0, // 2: xray.proxy.gmesh.inbound.Config.mode:type_name -> xray.proxy.gmesh.inbound.Config.Mode
	3, // 3: xray.proxy.gmesh.inbound.Config.discovery:type_name -> xray.proxy.gmesh.inbound.Config.Discovery
	4, // 4: xray.proxy.gmesh.inbound.Config.routing:type_name -> xray.proxy.gmesh.inbound.Config.Routing
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proxy_gmesh_inbound_config_proto_init() }
func file_proxy_gmesh_inbound_config_proto_init() {
	if File_proxy_gmesh_inbound_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_gmesh_inbound_config_proto_rawDesc), len(file_proxy_gmesh_inbound_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_gmesh_inbound_config_proto_goTypes,
		DependencyIndexes: file_proxy_gmesh_inbound_config_proto_depIdxs,
		EnumInfos:         file_proxy_gmesh_inbound_config_proto_enumTypes,
		MessageInfos:      file_proxy_gmesh_inbound_config_proto_msgTypes,
	}.Build()
	File_proxy_gmesh_inbound_config_proto = out.File
	file_proxy_gmesh_inbound_config_proto_goTypes = nil
	file_proxy_gmesh_inbound_config_proto_depIdxs = nil
}
